name: tsuperdriver
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 < 4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter:
  google_maps_flutter_web:
  overlay_support: 2.1.0
  flutter_styled_toast: ^2.1.3
  retrofit: ^4.1.0
  dio: ^5.5.0+1
  json_annotation: ^4.8.0
  json_serializable: ^6.6.0
  image_picker: ^1.0.4
  image: ^4.2.0
  shared_preferences: ^2.0.15
  google_places_flutter:
  geolocator:
  intl: ^0.19.0
  flutter_local_notifications:
  firebase_core: ^3.2.0
  firebase_storage:
  firebase_auth:
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons:

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/login/TsuperDriverIC.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 

flutter:
  uses-material-design: true
  assets:
    - assets/login/
