// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      // apiKey: 'AIzaSyD2ZttD1IlF7ZoK9FRKW3bL_shS_aSdzbA',
      // appId: '1:888416304840:web:4d164e0799e2ba3c26affd',
      // messagingSenderId: '888416304840',
      // projectId: 'rare-tome-409101',
      // authDomain: 'rare-tome-409101.firebaseapp.com',
      // storageBucket: 'rare-tome-409101.appspot.com',
      apiKey: "AIzaSyC7HBwtDOWOjeyZww_cHyJitPTGv8et8fA",
      authDomain: "tsuperapp2024-409911.firebaseapp.com",
      projectId: "tsuperapp2024-409911",
      storageBucket: "tsuperapp2024-409911.appspot.com",
      messagingSenderId: "517274138766",
      appId: "1:517274138766:web:265f8cafad154a2aba31df",
      measurementId: "G-2R5J53TLTN");

  static const FirebaseOptions android = FirebaseOptions(
      // apiKey: 'AIzaSyCZCaTuXQvl5onAL3dVTJi_58OE3U0s_5g',
      // appId: '1:888416304840:android:00708a8bae26252526affd',
      // messagingSenderId: '888416304840',
      // projectId: 'rare-tome-409101',
      // storageBucket: 'rare-tome-409101.appspot.com',
      apiKey: "AIzaSyC7HBwtDOWOjeyZww_cHyJitPTGv8et8fA",
      authDomain: "tsuperapp2024-409911.firebaseapp.com",
      projectId: "tsuperapp2024-409911",
      storageBucket: "tsuperapp2024-409911.appspot.com",
      messagingSenderId: "517274138766",
      appId: "1:517274138766:web:265f8cafad154a2aba31df",
      measurementId: "G-2R5J53TLTN");
}
